---
version: "3"
services:
  registrar:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    env_file: 
      - ./docker/env_file
      - chn-registrar.env
    ports:
      - 85:80
    volumes:
      - database:/app/data/
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - AUDIT_WRITE
  #revproxy:
  #  build:
  #    context: .
  #    dockerfile: nginx/Dockerfile
  #  ports:
      #- 443:443
  #    - 80:80
  #  cap_drop:
  #    - ALL
  #  cap_add:
  #    - NET_BIND_SERVICE
  #    - AUDIT_WRITE
  #    - CHOWN
  #    - SETGID
  #    - SETUID

volumes:
  database:
